-- phpMyAdmin SQL Dump
-- version 3.5.2.2
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Oct 04, 2016 at 03:34 PM
-- Server version: 5.5.27
-- PHP Version: 5.4.7

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `pemrogramanweb`
--

-- --------------------------------------------------------

--
-- Table structure for table `menu`
--

CREATE TABLE IF NOT EXISTS `menu` (
  `id_menu` varchar(5) NOT NULL,
  `nama_menu` varchar(100) NOT NULL,
  `harga` int(11) NOT NULL,
  `gambar` varchar(100) NOT NULL,
  `deskripsi` text NOT NULL,
  PRIMARY KEY (`id_menu`),
  UNIQUE KEY `id_menu` (`id_menu`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `menu`
--

INSERT INTO `menu` (`id_menu`, `nama_menu`, `harga`, `gambar`, `deskripsi`) VALUES
('MK001', 'NASI PUTIH', 0, 'NASI PUTIH.jpg', 'Berasal dari beras pilihan, dengan kualitas terbaik'),
('MK002', 'SAMBAL TERASI', 0, 'SAMBAL TERASI.jpg', 'Dibuat dengan cabai pilihan yang diolah dengan terasi berkualitas sebagai pelengkap saat menyantap hidangan agar terasa lebih nikmat.'),
('MK003', 'SAMBAL MANGGA', 0, 'SAMBAL MANGGA.jpg', 'Dibuat dengan cabai pilihan yang diolah dengan mangga muda berkualitas sebagai pelengkap saat menyantap hidangan agar terasa lebih nikmat'),
('MK004', 'SAYUR ASEM', 17000, 'SAYUR ASEM.jpg', 'Dibuat dengan bahan-bahan pilihan yang diolah dengan bumbu-bumbu terbaik yang dapat memberikan citarasa manis dan asam sebagai pelengkap saat menyantap hidangan agar terasa lebih nikmat.'),
('MK005', 'TAHU GORENG', 17000, 'TAHU GORENG.jpg', 'Berasal dari tahu yang diolah dari kedelai terbaik dengan bumbu-bumbu yang memiliki citarasa tinggi'),
('MK006', 'TEMPE GORENG', 17000, 'TEMPE GORENG.jpg', 'Berasal dari tempe yang diolah dari kedelai terbaik dengan bumbu-bumbu yang memiliki citarasa tinggi'),
('MK007', 'TAUGE IKAN ASIN', 22000, 'TAUGE IKAN ASIN.jpg', 'Dimasak dengan tauge segar dan ikan asin pilihan yang diberi bumbu khas yang akan memberikan citarasa tinggi'),
('MK008', 'KANGKUNG BALACAN', 22000, 'KANGKUNG BALACAN.jpg', 'Kangkung yang dimasak dengan campuran bahan dan bumbu yang khas yang terdiri dari bawang merah, bawang putih, terasi, dan ebi yang akan memberikan citarasa tinggi'),
('MK009', 'KANGKUNG BAWANG PUTIH', 22000, 'KANGKUNG BAWANG PUTIH.jpg', 'Kangkung yang dimasak dengan campuran bahan dan bumbu yang khas dari bawang putih serta bumbu yang lainnya yang memiliki citarasa tinggi'),
('MK010', 'KAILAN MUDA SAUS TIRAM', 22000, 'KAILAN MUDA SAUS TIRAM.jpg', 'Kailan yang dimasak dengan campuran bahan dan bumbu yang khas dari saus tiram dan bawang putih yang akan memberikan citarasa tinggi'),
('MK011', 'KERANG HIJAU SAUS PADANG', 30000, 'KERANG HIJAU SAUS PADANG.jpg', 'Kerang Hijau yang dimasak dengan campuran bahan dan bumbu saus padang yang memiliki rasa pedas, gurih dan manis yang akan memberikan citarasa tinggi'),
('MK012', 'KERANG HIJAU SAUS TIRAM', 30000, 'KERANG HIJAU SAUS TIRAM.jpg', 'Kerang Hijau yang dimasak dengan campuran bahan dan bumbu saus tiram yang memiliki rasa pedas, gurih dan manis yang akan memberikan citarasa tinggi'),
('MK013', 'NASI GORENG', 20000, 'NASI GORENG.jpg', 'Nasi yang dimasak dengan cara digoreng bersama campuran bahan dan bumbu khas seperti  kecap manis, bawang merah, bawang putih dan bumbu lainnya yang akan memberikan citarasa tinggi'),
('MK014', 'BAKMI GORENG', 20000, 'BAKMI GORENG.jpg', 'Bakmi yang dimasak dengan cara digoreng bersama campuran bahan dan bumbu khas seperti  kecap manis, bawang merah, bawang putih dan bumbu lainnya yang akan memberikan citarasa tinggi'),
('MK015', 'TAHU JEPANG SAUS PADANG', 30000, 'TAHU JEPANG SAUS PADANG.jpg', 'Tahu jepang pilihan yang terbuat dari olahan kedelai terbaik dimasak dengan campuran bahan dan bumbu saus padang yang memiliki rasa pedas, gurih dan manis yang akan memberikan citarasa tinggi'),
('MK016', 'TAHU JEPANG SAUS TIRAM', 30000, 'TAHU JEPANG SAUS TIRAM.jpg', 'Tahu jepang pilihan yang terbuat dari olahan kedelai terbaik dimasak dengan campuran bahan dan bumbu saus tiram yang memiliki rasa pedas, gurih dan manis yang akan memberikan citarasa tinggi'),
('MK017', 'TAHU JEPANG SAUS TELUR ASIN', 30000, 'TAHU JEPANG SAUS TELUR ASIN.jpg', 'Tahu jepang pilihan yang terbuat dari olahan kedelai terbaik dimasak dengan campuran bahan dan bumbu saus telur asin yang memiliki rasa gurih yang akan memberikan citarasa tinggi'),
('MK018', 'SUP TOM YAM', 32000, 'SUP TOM YAM.jpg', 'Sup yang berasal dari negara Thailand yang terbuat dari campuran bahan dan bumbu khas yang memiliki rasa pedas, asam dan manis yang akan memberikan citarasa tinggi'),
('MK019', 'SUP SEAFOOD', 32000, 'SUP SEAFOOD.jpg', 'Sup yang terbuat dari campuran bahan dan bumbu khas dengan tambahan seafood yang akan memberikan citarasa tinggi'),
('MK020', 'BUNCIS MUDA ALA SINGAPORE', 30000, 'BUNCIS MUDA ALA SINGAPORE.jpg', 'Tumis buncis ala Singapore ini akan memberikan sensasi yang berbeda, yaitu terbuat dari campuran bahan dan bumbu khas yang akan memberikan citarasa tinggi'),
('MK021', 'NASI GORENG SEAFOOD', 30000, 'NASI GORENG SEAFOOD.jpg', 'Nasi yang dimasak dengan cara digoreng bersama campuran bahan dan bumbu khas seperti  kecap manis, bawang merah, bawang putih dan bumbu lainnya dengan tambahan seafood yang akan memberikan citarasa tinggi'),
('MK022', 'BAKMI GORENG SEAFOOD', 30000, 'BAKMI GORENG SEAFOOD.jpg', 'Bakmi yang dimasak dengan cara digoreng bersama campuran bahan dan bumbu khas seperti  kecap manis, bawang merah, bawang putih dan bumbu lainnya dengan tambahan seafood yang akan memberikan citarasa tinggi'),
('MK023', 'OMELETE SEAFOOD', 39000, 'OMELETE SEAFOOD.jpg', 'Telur dadar yang dimasak dari campuran bahan dan bumbu khas dengan tambahan seafood yang akan memberikan citarasa tinggi'),
('MK024', 'AYAM FILLET SAMBAL RICA', 45000, 'AYAM FILLET SAMBAL RICA.jpg', 'Daging ayam yang difillet dan dimasak dengan campuran bahan dan bumbu khas yang memiliki rasa pedas dan gurih yang akan memberikan citarasa tinggi'),
('MK025', 'AYAM FILLET SAUS ASAM MANIS', 45000, 'AYAM FILLET SAUS ASAM MANIS.jpg', 'Daging ayam yang difillet dan dimasak dengan campuran bahan dan bumbu khas yang memiliki rasa gurih, asam dan manis yang akan memberikan citarasa tinggi'),
('MK026', 'AYAM FILLET SAUS LADA HITAM', 45000, 'AYAM FILLET SAUS LADA HITAM.jpg', 'Daging ayam yang difillet dan dimasak dengan campuran bahan dan bumbu khas saus lada hitam yang memiliki rasa pedas dan gurih yang akan memberikan citarasa tinggi'),
('MK027', 'CUMI GORENG SAUS TELUR ASIN', 55000, 'CUMI GORENG SAUS TELUR ASIN.jpg', 'Cumi yang digoreng dan dimasak dengan campuran bahan dan bumbu saus telur asin yang memiliki rasa gurih akan memberikan citarasa yang tinggi'),
('MK028', 'CUMI GORENG SAUS PADANG', 55000, 'CUMI GORENG SAUS PADANG.jpg', 'Cumi yang digoreng dan dimasak dengan campuran bahan dan bumbu khas saus padang yang memiliki rasa pedas, manis, dan gurih yang akan memberikan citarasa tinggi'),
('MK029', 'CUMI GORENG CABE GARAM', 35000, 'CUMI GORENG CABE GARAM.jpg', 'Cumi yang digoreng dan dimasak dengan campuran bahan dan bumbu khas yang memiliki rasa gurih dan pedas yang akan memberikan citarasa tinggi'),
('MK030', 'CUMI GORENG KREMES', 35000, 'CUMI GORENG KREMES.jpg', 'Cumi yang digoreng dan dimasak dengan campuran bahan dan bumbu khas sehingga cumi akan terasa renyah dan memiliki rasa gurih yang akan memberikan citarasa tinggi'),
('MK031', 'CUMI BAKAR KECAP', 65000, 'CUMI BAKAR KECAP.jpg', 'Cumi yang dibakar dengan campuran bahan dan bumbu khas serta olesan kecap manis sehingga memiliki rasa manis dan gurih yang akan memberikan citarasa tinggi'),
('MK032', 'CUMI BAKAR PEDAS', 65000, 'CUMI BAKAR PEDAS.jpg', 'Cumi yang dibakar dengan campuran bahan dan bumbu cabai yang khas sehingga memiliki rasa pedas, manis dan gurih yang akan memberikan citarasa tinggi'),
('MK033', 'IKAN FILLET SAUS MANGGA', 50000, 'IKAN FILLET SAUS MANGGA.jpg', 'Ikan fillet yang dimasak dengan campuran bahan dan bumbu khas saus mangga akan memberikan citarasa tinggi'),
('MK034', 'IKAN FILLET SAUS ASAM MANIS', 50000, 'IKAN FILLET SAUS ASAM MANIS.jpg', 'Ikan fillet yang dimasak dengan campuran bahan dan bumbu khas saus asam manis akan memberikan citarasa tinggi'),
('MK035', 'KEPITING SOKA KREMES', 71000, 'KEPITING SOKA KREMES.jpg', 'Kepiting soka yang digoreng dengan tepung kremes serta campuran bahan dan bumbu khas akan memberikan citarasa tinggi'),
('MK036', 'KEPITING SOKA MASAK TELUR ASIN', 71000, 'KEPITING SOKA MASAK TELUR ASIN.jpg', 'Kepiting soka yang dimasak dengan telur asin serta campuran bahan dan bumbu khas akan memberikan citarasa tinggi'),
('MK037', 'UDANG SAUS TELUR ASIN', 67000, 'UDANG SAUS TELUR ASIN.jpg', 'Udang pilihan yang dimasak dengan campuran bahan dan bumbu khas saus telur asin akan memberikan citarasa tinggi'),
('MK038', 'UDANG SAUS PADANG', 67000, 'UDANG SAUS PADANG.jpg', 'Udang pilihan yang dimasak dengan campuran bahan dan bumbu khas saus padang akan memberikan citarasa tinggi'),
('MK039', 'UDANG SAUS MAYONAISE', 67000, 'UDANG SAUS MAYONAISE.jpg', 'Udang pilihan yang dimasak dengan campuran bahan dan bumbu khas saus mayonaise akan memberikan citarasa tinggi'),
('MK040', 'KERANG BAMBU SAUS PADANG', 39000, 'KERANG BAMBU SAUS PADANG.jpg', 'Kerang bambu pilihan yang dimasak dengan campuran bahan dan bumbu khas saus padang akan memberikan citarasa tinggi'),
('MK041', 'KERANG BAMBU SAUS TIRAM', 39000, 'KERANG BAMBU SAUS TIRAM.jpg', 'Kerang bambu pilihan yang dimasak dengan campuran bahan dan bumbu khas saus tiram akan memberikan citarasa tinggi'),
('MK042', 'IKAN FILLET SAUS ORIENTAL', 50000, 'IKAN FILLET SAUS ORIENTAL.jpg', 'Ikan fillet pilihan yang dimasak dengan campuran bahan dan bumbu khas saus oriental akan memberikan citarasa tinggi'),
('MK043', 'ALUNG UNAGI', 53000, 'ALUNG UNAGI.jpg', 'Belut pilihan yang dimasak dengan campuran bahan dan bumbu khas cabai yang memiliki rasa gurih dan pedas yang akan memberikan citarasa tinggi'),
('MK044', 'JAMUR TIRAM CABE GARAM', 22000, 'JAMUR TIRAM CABE GARAM.jpg', 'Jamur tiram yang dimasak dengan campuran bahan dan bumbu khas yang memiliki rasa gurih dan pedas yang akan memberikan citarasa tinggi'),
('MK045', 'CUMI GORENG TEPUNG', 55000, 'CUMI GORENG TEPUNG.jpg', 'Cumi yang digoreng dan dimasak dengan baluran tepung dan bumbu khas akan memberikan citarasa tinggi'),
('MK046', 'NASI GORENG MERAH', 20000, 'NASI GORENG MERAH.jpg', 'Nasi putih yang di masak dengan saos tomat Banjar ini dapat di modifikasi menjadi nasi goring merah. Dengan rasa tomatnya yang tidak cenderung asam dapat di santap oleh kalangan anak muda sampai orang tua.'),
('MK047', 'KANGKUNG PLECING', 22000, 'KANGKUNG PLECING.jpg', 'Plecing adalah masakan khas Indonesia yang berasal dari Lombok.  Plecing kangkung terdiri dari kangkung yang direbus dan disajikan dalam keadaan dingin dan segar dengan salmbal tomat yang dibuat dari cabe rawit, garam terasi dan tomat dan kadangkala diberi tetesan jeruk limau. '),
('MK048', 'NASI GORENG ASIAN', 30000, 'NASI GORENG ASIAN.jpg', 'Nasi goreng dengan bumbu khas dari Negara Cina ini menjadi santapan lezat favorit di kalangan anak muda. '),
('MK049', 'KWETIAW GORENG SEAFOOD', 30000, 'KWETIAW GORENG SEAFOOD.jpg', 'Kwetiaw yang di goreng ini di campurkan dengan seafood seperti potongan cumi, udang, ataupun campuran daging ikan, taklupa dengan sayurnya juga.'),
('MK050', 'AYAM GORENG TERASI', 45000, 'AYAM GORENG TERASI.jpg', 'Ayam yang biasanya di goreng ini di campurkan dengan bumbu terasi yang sangat lezat. '),
('MK051', 'AYAM FILLET TEPUNG ROTI', 45000, 'AYAM FILLET TEPUNG ROTI.jpg', 'Ayam yang di fillet (kulit dan tulangnya di buang) ini di campurkan dengan tepung roti kemudian di goreng. '),
('MK052', 'TAHU BAKAR', 17000, 'TAHU BAKAR.jpg', 'Tahu yang biasanya digoreng, kali ini disajikan dengan cara di bakar, dengan kecap yang manis membuat tahunya makin lezat.'),
('MK053', 'TEMPE BAKAR', 17000, 'TEMPE BAKAR.jpg', 'Tempe yang biasanya digoreng, kali ini disajikan dengan cara di bakar, dengan kecap yang manis membuat tahunya makin lezat.'),
('MK054', 'SAYUR KOMBINASI', 22000, 'SAYUR KOMBINASI.jpg', 'Sayuran yang dimasak dengan campuran bahan seperti wortel, kailan dan jamur dan bumbu khas yang memiliki rasa gurih dan lezat akan memberikan citarasa yang tinggi'),
('MK055', 'NASI GORENG MERAH SEAFOOD', 30000, 'NASI GORENG MERAH SEAFOOD.jpg', 'Nasi goreng merah seafood ini di masak dengan saos tomat yang tidak terlalu asam. Saos tomat yang lebih cenderung ke manis ini bisa di makan oleh semua kalangan, apalagi di campur dengan udang dan cumi. '),
('MK056', 'UDANG BAKAR KECAP', 67000, 'UDANG BAKAR KECAP.jpg', 'Udang dimasak dengan cara dibakar dengan campuran bahan dan bumbu khas serta tambahan kecap yang memiliki rasa gurih dan manis akan memberikan citarasa yang tinggi'),
('MK057', 'UDANG BAKAR PEDAS', 67000, 'UDANG BAKAR PEDAS.jpg', 'Udang dimasak dengan cara dibakar dengan campuran bahan dan bumbu khas serta tambahan kecap dan cabai yang memiliki rasa pedas, gurih dan manis akan memberikan citarasa yang tinggi'),
('MK058', 'UDANG SAUS MONGOLIAN', 55000, 'UDANG SAUS MONGOLIAN.jpg', 'Udang yang di goreng kemudian direndamkan langsung dengan saos khas Mongolian akan memberikan citarasa yang tinggi'),
('MK059', 'AYAM FILLET SAUS MONGOLIAN', 45000, 'AYAM FILLET SAUS MONGOLIAN.jpg', 'Ayam fillet yang di goreng kemudian direndamkan langsung dengan saos khas Mongolian akan memberikan citarasa yang tinggi'),
('MK060', 'MIE SIRAM CRISPY', 30000, 'MIE SIRAM CRISPY.jpg', 'Mie yang di rebus setengah matang ini kemuedian di campurkan dengan saos khas Aceh akan memberikan citarasa yang tinggi'),
('MK061', 'UDANG SAUS ASAM MANIS', 66000, 'UDANG SAUS ASAM MANIS.jpg', 'Udang dengan saos asam manis ini di buat dengan mencampurkan saos cabai dengan saos tomat dan menghasilkan rasa asam manis yang memiliki citarasa yang tinggi'),
('MK062', 'SAPI LADA HITAM', 67000, 'SAPI LADA HITAM.jpg', 'Daging sapi pilihan yang dimasak dengan campuran bahan dan bumbu saos lada hitam yang khas akan memberikan citarasa tinggi'),
('MK063', 'TAHU KIPAS', 39000, 'TAHU KIPAS.jpg', 'Tahu yang di iris tipis dan bentuknya seperti kipas ini langsung di goreng dengan minyak panas agar bentuknya tetap seperti kipas ini memiliki citarasa yang tinggi'),
('MK064', 'CUMI BABY GORENG TEPUNG', 45000, 'CUMI BABY GORENG TEPUNG.jpg', 'Cumi baby pilihan yang digoreng dengan tepung serta dengan campuran bahan dan bumbu khas akan memberikan citarasa tinggi'),
('MK065', 'TAHU GORENG CABE GARAM', 24000, 'TAHU GORENG CABE GARAM.jpg', 'Tahu yang digoreng dengan campuran bahan dan bumbu cabai dan garam yang khas sehingga memiliki rasa pedas dan gurih yang akan memberikan citarasa tinggi'),
('MK066', 'AYAM FILLET SAUS ORIENTAL', 45000, 'AYAM FILLET SAUS ORIENTAL.jpg', 'Ayam fillet yang dimasak dengan saos oriental ini adalah masakah khas Cina yang memiliki citarasa tinggi'),
('MK067', 'UDANG MAYO CHILLI', 55000, 'UDANG MAYO CHILLI.jpg', 'Udang pilihan yang digoreng dengan campuran bahan dan bumbu khas yang kemudian di tambahkan chilli mayo akan memberikan citarasa yang tinggi'),
('MK068', 'SAPI SAUS MONGOLIAN', 67000, 'SAPI SAUS MONGOLIAN.jpg', 'Daging sapi pilihan dimasak dengan campuran bahan dan bumbu khas saus mongolian yang akan memberikan citarasa tinggi'),
('MK069', 'CUMI KEPALA SAUS MONGOLIAN', 35000, 'CUMI KEPALA SAUS MONGOLIAN.jpg', 'Cumi kepala dimasak dengan campuran bahan dan bumbu khas saus mongolian yang akan memberikan citarasa tinggi'),
('MK070', 'JAMUR GORENG SAUS ORIENTAL', 22000, 'JAMUR GORENG SAUS ORIENTAL.jpg', 'Jamur yang digoreng dan dimasak dengan campuran bahan dan bumbu khas saus oriental yang akan memberikan citarasa tinggi'),
('MK071', 'JAMUR GORENG SAMBAL RICA', 22000, 'JAMUR GORENG SAMBAL RICA.jpg', 'Jamur yang di goreng dengan sambal rica ini terdiri dari sambal merah dengan perpaduan asam manis.'),
('MK072', 'IKAN BANDENG BAKAR KECAP', 54000, 'IKAN BANDENG BAKAR KECAP.jpg', 'Ikan bandeng pilihan yang dibakar dengan campuran bahan dan bumbu khas serta tambahan kecap manis akan memberikan citarasa tinggi'),
('MK073', 'IKAN BANDENG BAKAR PEDAS', 54000, 'IKAN BANDENG BAKAR PEDAS.jpg', 'Ikan bandeng pilihan yang dibakar dengan campuran bahan dan bumbu khas serta tambahan cabai akan memberikan citarasa tinggi'),
('MK074', 'IKAN BANDENG BAKAR RICA', 54000, 'IKAN BANDENG BAKAR RICA.jpg', 'Ikan bandeng pilihan yang dibakar dengan campuran bahan dan bumbu khas rica akan memberikan citarasa tinggi'),
('MK075', 'IKAN PATIN BAKAR KECAP (SEDANG)', 70000, 'IKAN PATIN BAKAR KECAP (SEDANG).jpg', 'Ikan patin pilihan berukuran sedang yang dibakar dengan campuran bahan dan bumbu khas serta tambahan kecap manis akan memberikan citarasa tinggi'),
('MK076', 'IKAN PATIN BAKAR PEDAS (SEDANG)', 70000, 'IKAN PATIN BAKAR PEDAS (SEDANG).jpg', 'Ikan patin pilihan berukuran sedang yang dibakar dengan campuran bahan dan bumbu khas pedas akan memberikan citarasa tinggi'),
('MK077', 'IKAN PATIN BAKAR KECAP (BESAR)', 80000, 'IKAN PATIN BAKAR KECAP (BESAR).jpg', 'Ikan patin pilihan berukuran besar yang dibakar dengan campuran bahan dan bumbu khas serta tambahan kecap manis akan memberikan citarasa tinggi'),
('MK078', 'IKAN PATIN BAKAR PEDAS (BESAR)', 80000, 'IKAN PATIN BAKAR PEDAS (BESAR).jpg', 'Ikan patin pilihan berukuran besar yang dibakar dengan campuran bahan dan bumbu khas pedas akan memberikan citarasa tinggi'),
('MK079', 'IKAN PATIN TIM KECAP (SEDANG)', 70000, 'IKAN PATIN TIM KECAP (SEDANG).jpg', 'Ikan patin pilihan berukuran sedang yang dikukus dengan campuran bahan dan bumbu khas serta tambahan kecap manis akan memberikan citarasa tinggi'),
('MK080', 'IKAN PATIN TIM BAWANG PUTIH (SEDANG)', 70000, 'IKAN PATIN TIM BAWANG PUTIH (SEDANG).jpg', 'Ikan patin pilihan berukuran sedang yang dikukus dengan campuran bahan dan bumbu khas bawang putih akan memberikan citarasa tinggi'),
('MK081', 'IKAN PATIN TIM KECAP (BESAR)', 80000, 'IKAN PATIN TIM KECAP (BESAR).jpg', 'Ikan patin pilihan berukuran besar yang dikukus dengan campuran bahan dan bumbu khas serta tambahan kecap manis akan memberikan citarasa tinggi'),
('MK082', 'IKAN PATIN TIM BAWANG PUTIH (BESAR)', 80000, 'IKAN PATIN TIM BAWANG PUTIH (BESAR).jpg', 'Ikan patin pilihan berukuran besar yang dikukus dengan campuran bahan dan bumbu khas bawang putih akan memberikan citarasa tinggi'),
('MK083', 'IKAN GURAMI GORENG (NORMAL)', 70000, 'IKAN GURAMI GORENG (NORMAL).jpg', 'Ikan gurami pilihan berukuran normal yang digoreng dengan campuran bahan dan bumbu khas akan memberikan citarasa tinggi'),
('MK084', 'IKAN GURAMI GORENG (SEDANG)', 80000, 'IKAN GURAMI GORENG (SEDANG).jpg', 'Ikan gurami pilihan berukuran sedang yang digoreng dengan campuran bahan dan bumbu khas akan memberikan citarasa tinggi'),
('MK085', 'IKAN GURAMI GORENG (BESAR)', 90000, 'IKAN GURAMI GORENG (BESAR).jpg', 'Ikan gurami pilihan berukuran besar yang digoreng dengan campuran bahan dan bumbu khas akan memberikan citarasa tinggi'),
('MK086', 'IKAN GURAMI BAKAR KECAP (NORMAL)', 70000, 'IKAN GURAMI BAKAR KECAP (NORMAL).jpg', 'Ikan gurami pilihan berukuran normal yang dibakar dengan campuran bahan dan bumbu khas serta tambahan kecap manis akan memberikan citarasa tinggi'),
('MK087', 'IKAN GURAMI BAKAR KECAP (SEDANG)', 80000, 'IKAN GURAMI BAKAR KECAP (SEDANG).jpg', 'Ikan gurami pilihan berukuran sedang yang dibakar dengan campuran bahan dan bumbu khas serta tambahan kecap manis akan memberikan citarasa tinggi'),
('MK088', 'IKAN GURAMI BAKAR KECAP (BESAR)', 90000, 'IKAN GURAMI BAKAR KECAP (BESAR).jpg', 'Ikan gurami pilihan berukuran besar yang dibakar dengan campuran bahan dan bumbu khas serta tambahan kecap manis akan memberikan citarasa tinggi'),
('MK089', 'IKAN KAKAP BAKAR KECAP (NORMAL)', 71000, 'IKAN KAKAP BAKAR KECAP (NORMAL).jpg', 'Ikan kakap pilihan berukuran normal yang dibakar dengan campuran bahan dan bumbu khas serta tambahan kecap manis akan memberikan citarasa tinggi'),
('MK090', 'IKAN KAKAP BAKAR PEDAS (NORMAL)', 71000, 'IKAN KAKAP BAKAR PEDAS (NORMAL).jpg', 'Ikan kakap pilihan berukuran normal yang dibakar dengan campuran bahan dan bumbu khas pedas akan memberikan citarasa tinggi'),
('MK091', 'IKAN KAKAP BAKAR RICA (NORMAL)', 71000, 'IKAN KAKAP BAKAR RICA (NORMAL).jpg', 'Ikan kakap pilihan berukuran normal yang dibakar dengan campuran bahan dan bumbu khas rica akan memberikan citarasa tinggi'),
('MK092', 'IKAN KAKAP BAKAR KECAP (SEDANG)', 81000, 'IKAN KAKAP BAKAR KECAP (SEDANG).jpg', 'Ikan kakap pilihan berukuran sedang yang dibakar dengan campuran bahan dan bumbu khas serta tambahan kecap manis akan memberikan citarasa tinggi'),
('MK093', 'IKAN KAKAP BAKAR PEDAS (SEDANG)', 81000, 'IKAN KAKAP BAKAR PEDAS (SEDANG).jpg', 'Ikan patin pilihan berukuran sedang yang dibakar dengan campuran bahan dan bumbu khas pedas akan memberikan citarasa tinggi'),
('MK094', 'IKAN KAKAP BAKAR RICA (SEDANG)', 81000, 'IKAN KAKAP BAKAR RICA (SEDANG).jpg', 'Ikan kakap pilihan berukuran sedang yang dibakar dengan campuran bahan dan bumbu khas pedas akan memberikan citarasa tinggi'),
('MK095', 'IKAN KAKAP BAKAR KECAP (BESAR)', 91000, 'IKAN KAKAP BAKAR KECAP (BESAR).jpg', 'Ikan kakap pilihan berukuran besar yang dibakar dengan campuran bahan dan bumbu khas serta tambahan kecap manis akan memberikan citarasa tinggi'),
('MK096', 'IKAN KAKAP BAKAR PEDAS (BESAR)', 91000, 'IKAN KAKAP BAKAR PEDAS (BESAR).jpg', 'Ikan kakap pilihan berukuran besar yang dibakar dengan campuran bahan dan bumbu khas pedas akan memberikan citarasa tinggi'),
('MK097', 'IKAN KAKAP BAKAR RICA (BESAR)', 91000, 'IKAN KAKAP BAKAR RICA (BESAR).jpg', 'Ikan kakap pilihan berukuran besar yang dibakar dengan campuran bahan dan bumbu khas rica akan memberikan citarasa tinggi'),
('MK098', 'IKAN AYAM-AYAM SAUS ASAM MANIS', 54000, 'IKAN AYAM-AYAM SAUS ASAM MANIS.jpg', 'Ikan ayam-ayam pilihan yang dimasak dengan campuran bahan dan bumbu khas saus asam manis akan memberikan citarasa tinggi'),
('MK099', 'IKAN AYAM-AYAM BAKAR KUNING', 54000, 'IKAN AYAM-AYAM BAKAR KUNING.jpg', 'Ikan ayam-ayam pilihan yang dimasak dengan campuran bahan dan bumbu khas kunyit akan memberikan citarasa tinggi'),
('MK100', 'IKAN GURAME GORENG SAUS SPESIAL (SEDANG)', 80000, 'IKAN GURAME GORENG SAUS SPESIAL (SEDANG).jpg', 'Ikan gurame pilihan berukuran sedang yang dimasak dengan campuran bahan dan bumbu khas saus spesial akan memberikan citarasa tinggi'),
('MK101', 'IKAN GURAME GORENG SAUS SPESIAL (BESAR)', 90000, 'IKAN GURAME GORENG SAUS SPESIAL (BESAR).jpg', 'Ikan gurame pilihan berukuran besar yang dimasak dengan campuran bahan dan bumbu khas saus spesial akan memberikan citarasa tinggi'),
('MK102', 'IKAN GURAME GORENG SAUS ASAM MANIS', 80000, 'IKAN GURAME GORENG SAUS ASAM MANIS.jpg', 'Ikan gurame pilihan yang digoreng dan dimasak dengan campuran bahan dan bumbu khas saus asam manis akan memberikan citarasa tinggi'),
('MK103', 'IKAN GURAME BAKAR PEDAS (NORMAL)', 70000, 'IKAN GURAME BAKAR PEDAS (NORMAL).jpg', 'Ikan gurame pilihan berukuran normal yang dibakar dengan campuran bahan dan bumbu khas pedas akan memberikan citarasa tinggi'),
('MK104', 'IKAN GURAME BAKAR PEDAS (SEDANG)', 80000, 'IKAN GURAME BAKAR PEDAS (SEDANG).jpg', 'Ikan gurame pilihan berukuran sedang yang dibakar dengan campuran bahan dan bumbu khas pedas akan memberikan citarasa tinggi'),
('MK105', 'IKAN GURAME BAKAR PEDAS (BESAR)', 90000, 'IKAN GURAME BAKAR PEDAS (BESAR).jpg', 'Ikan gurame pilihan berukuran besar yang dibakar dengan campuran bahan dan bumbu khas pedas akan memberikan citarasa tinggi'),
('MK106', 'IKAN KERAPU BAKAR KECAP (NORMAL)', 71000, 'IKAN KERAPU BAKAR KECAP (NORMAL).jpg', 'Ikan kerapu pilihan berukuran normal yang dibakar dengan campuran bahan dan bumbu khas serta tambahan kecap manis akan memberikan citarasa tinggi'),
('MK107', 'IKAN KERAPU BAKAR KECAP (SEDANG)', 81000, 'IKAN KERAPU BAKAR KECAP (SEDANG).jpg', 'Ikan kerapu pilihan berukuran sedang yang dibakar dengan campuran bahan dan bumbu khas serta tambahan kecap manis akan memberikan citarasa tinggi'),
('MK108', 'IKAN KERAPU BAKAR KECAP (BESAR)', 91000, 'IKAN KERAPU BAKAR KECAP (BESAR).jpg', 'Ikan kerapu pilihan berukuran besar yang dibakar dengan campuran bahan dan bumbu khas serta tambahan kecap manis akan memberikan citarasa tinggi'),
('MK109', 'IKAN PATIN BAKAR RICA (SEDANG)', 70000, 'IKAN PATIN BAKAR RICA (SEDANG).jpg', 'Ikan patin pilihan berukuran sedang yang dibakar dengan campuran bahan dan bumbu khas rica akan memberikan citarasa tinggi'),
('MK110', 'IKAN PATIN BAKAR RICA (BESAR)', 80000, 'IKAN PATIN BAKAR RICA (BESAR).jpg', 'Ikan patin pilihan berukuran besar yang dibakar dengan campuran bahan dan bumbu khas rica akan memberikan citarasa tinggi'),
('MK111', 'IKAN KAKAP GORENG TEPUNG (NORMAL)', 71000, 'IKAN KAKAP GORENG TEPUNG (NORMAL).jpg', 'Rasa gurih dari daging ikan kakap yang lembut dan berpadu dengan tepung bumbu yang renyah akan membuat rasanya semakin istimewa. 1 ekor ikan kakap ukuran normal goreng tepung siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK112', 'IKAN KAKAP GORENG TEPUNG (SEDANG)', 81000, 'IKAN KAKAP GORENG TEPUNG (SEDANG).jpg', 'Rasa gurih dari daging ikan kakap yang lembut dan berpadu dengan tepung bumbu yang renyah akan membuat rasanya semakin istimewa. 1 ekor ikan kakap ukuran sedang goreng tepung siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK113', 'IKAN KAKAP GORENG TEPUNG (BESAR)', 91000, 'IKAN KAKAP GORENG TEPUNG (BESAR).jpg', 'Rasa gurih dari daging ikan kakap yang lembut dan berpadu dengan tepung bumbu yang renyah akan membuat rasanya semakin istimewa. 1 ekor ikan kakap ukuran besar goreng tepung siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK114', 'IKAN KERAPU GORENG TEPUNG (NORMAL)', 71000, 'IKAN KERAPU GORENG TEPUNG (NORMAL).jpg', 'Rasa gurih dari daging ikan kerapu yang lembut dan berpadu dengan tepung bumbu yang renyah akan membuat rasanya semakin istimewa. 1 ekor ikan kerapu ukuran normal goreng tepung siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK115', 'IKAN KERAPU GORENG TEPUNG (SEDANG)', 81000, 'IKAN KERAPU GORENG TEPUNG (SEDANG).jpg', 'Rasa gurih dari daging ikan kerapu yang lembut dan berpadu dengan tepung bumbu yang renyah akan membuat rasanya semakin istimewa. 1 ekor ikan kerapu ukuran sedang goreng tepung siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK116', 'IKAN KERAPU GORENG TEPUNG (BESAR)', 91000, 'IKAN KERAPU GORENG TEPUNG (BESAR).jpg', 'Rasa gurih dari daging ikan kerapu yang lembut dan berpadu dengan tepung bumbu yang renyah akan membuat rasanya semakin istimewa. 1 ekor ikan kerapu ukuran besar goreng tepung siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK117', 'IKAN GURAME BAKAR RICA (NORMAL)', 70000, 'IKAN GURAME BAKAR RICA (NORMAL).jpg', 'Ikan gurame memiliki daging yang empuk dan gurih. Disertai dengan bumbu rica yang berwarna oranye kemerahan dengan cabe rawit yang pedas serta aroma kunyit dan potongan tomat merah, irisan bawang merah. 1 ekor ikan gurame bakar ukuran normal rica siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK118', 'IKAN GURAME BAKAR RICA (SEDANG)', 80000, 'IKAN GURAME BAKAR RICA (SEDANG).jpg', 'Ikan gurame memiliki daging yang empuk dan gurih. Disertai dengan bumbu rica yang berwarna oranye kemerahan dengan cabe rawit yang pedas serta aroma kunyit dan potongan tomat merah, irisan bawang merah. 1 ekor ikan gurame bakar ukuran sedang rica siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK119', 'IKAN GURAME BAKAR RICA (BESAR)', 90000, 'IKAN GURAME BAKAR RICA (BESAR).jpg', 'Ikan gurame memiliki daging yang empuk dan gurih. Disertai dengan bumbu rica yang berwarna oranye kemerahan dengan cabe rawit yang pedas serta aroma kunyit dan potongan tomat merah, irisan bawang merah. 1 ekor ikan gurame bakar ukuran besar rica siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK120', 'IKAN BARONANG BAKAR KECAP (NORMAL)', 71000, 'IKAN BARONANG BAKAR KECAP (NORMAL).jpg', 'Ikan baronang salah satu ikan air laut yang bisa dikonsumsi karena ikan baronang sendiri memiliki daging yang empuk dan gurih. Disertai dengan kecap manis pedas, rasanya gurih dan pas untuk lauk makan. 1 ekor ikan baronang bakar ukuran normal kecap siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK121', 'IKAN BARONANG BAKAR PEDAS (NORMAL)', 71000, 'IKAN BARONANG BAKAR PEDAS (NORMAL).jpg', 'Ikan baronang salah satu ikan air laut yang bisa dikonsumsi karena ikan baronang sendiri memiliki daging yang empuk dan gurih. Disertai dengan sambal pedas, rasanya pedas dan manis, pas untuk lauk makan. 1 ekor ikan baronang ukuran normal bakar pedas ukuran sedang kecap siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK122', 'IKAN BARONANG BAKAR RICA (NORMAL)', 71000, 'IKAN BARONANG BAKAR RICA (NORMAL).jpg', 'Ikan baronang salah satu ikan air laut yang bisa dikonsumsi karena ikan baronang sendiri memiliki daging yang empuk dan gurih. Disertai dengan bumbu rica yang berwarna oranye kemerahan dengan cabe rawit yang pedas serta aroma kunyit dan potongan tomat merah, irisan bawang merah. 1 ekor ikan baronang ukuran normal rica siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK123', 'IKAN BARONANG BAKAR KECAP (SEDANG)', 81000, 'IKAN BARONANG BAKAR KECAP (SEDANG).jpg', 'Ikan baronang salah satu ikan air laut yang bisa dikonsumsi karena ikan baronang sendiri memiliki daging yang empuk dan gurih. Disertai dengan kecap manis pedas, rasanya gurih dan pas untuk lauk makan. 1 ekor ikan baronang bakar ukuran sedang kecap siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK124', 'IKAN BARONANG BAKAR PEDAS (SEDANG)', 81000, 'IKAN BARONANG BAKAR PEDAS (SEDANG).jpg', 'Ikan baronang salah satu ikan air laut yang bisa dikonsumsi karena ikan baronang sendiri memiliki daging yang empuk dan gurih. Disertai dengan sambal pedas, rasanya pedas dan manis, pas untuk lauk makan. 1 ekor ikan baronang ukuran sedang bakar pedas ukuran sedang kecap siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK125', 'IKAN BARONANG BAKAR RICA (SEDANG)', 81000, 'IKAN BARONANG BAKAR RICA (SEDANG).jpg', 'Ikan baronang salah satu ikan air laut yang bisa dikonsumsi karena ikan baronang sendiri memiliki daging yang empuk dan gurih. Disertai dengan bumbu rica yang berwarna oranye kemerahan dengan cabe rawit yang pedas serta aroma kunyit dan potongan tomat merah, irisan bawang merah. 1 ekor ikan baronang ukuran sedang rica siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK126', 'IKAN BARONANG BAKAR KECAP (BESAR)', 91000, 'IKAN BARONANG BAKAR KECAP (BESAR).jpg', 'Ikan baronang salah satu ikan air laut yang bisa dikonsumsi karena ikan baronang sendiri memiliki daging yang empuk dan gurih. Disertai dengan kecap manis pedas, rasanya gurih dan pas untuk lauk makan. 1 ekor ikan baronang ukuran besar bakar kecap siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK127', 'IKAN BARONANG BAKAR PEDAS (BESAR)', 91000, 'IKAN BARONANG BAKAR PEDAS (BESAR).jpg', 'Ikan baronang salah satu ikan air laut yang bisa dikonsumsi karena ikan baronang sendiri memiliki daging yang empuk dan gurih. Disertai dengan sambal pedas, rasanya pedas dan manis, pas untuk lauk makan. 1 ekor ikan baronang ukuran besar bakar pedas ukuran sedang kecap siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK128', 'IKAN BARONANG BAKAR RICA (BESAR)', 91000, 'IKAN BARONANG BAKAR RICA (BESAR).jpg', 'Ikan baronang salah satu ikan air laut yang bisa dikonsumsi karena ikan baronang sendiri memiliki daging yang empuk dan gurih. Disertai dengan bumbu rica yang berwarna oranye kemerahan dengan cabe rawit yang pedas serta aroma kunyit dan potongan tomat merah, irisan bawang merah. 1 ekor ikan baronang ukuran besar rica siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK129', 'IKAN BAWAL BINTANG BAKAR KECAP (NORMAL)', 71000, 'IKAN BAWAL BINTANG BAKAR KECAP (NORMAL).jpg', 'Ikan bawal bintang memiliki daging yang empuk dan gurih. Disertai dengan kecap manis pedas, rasanya gurih dan pas untuk lauk makan. 1 ekor ikan bawal bintang bakar ukuran normal kecap siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK130', 'IKAN BAWAL BINTANG BAKAR PEDAS (NORMAL)', 71000, 'IKAN BAWAL BINTANG BAKAR PEDAS (NORMAL).jpg', 'Ikan bawal bintang memiliki daging yang empuk dan gurih. Disertai dengan sambal pedas, rasanya pedas dan manis, pas untuk lauk makan. 1 ekor ikan bawal bintang bakar ukuran normal pedas siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK131', 'IKAN BAWAL BINTANG BAKAR RICA (NORMAL)', 71000, 'IKAN BAWAL BINTANG BAKAR RICA (NORMAL).jpg', 'Ikan bawal bintang memiliki daging yang empuk dan gurih. Disertai dengan bumbu rica yang berwarna oranye kemerahan dengan cabe rawit yang pedas serta aroma kunyit dan potongan tomat merah, irisan bawang merah. 1 ekor ikan bawal bintang bakar ukuran normal rica siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK132', 'IKAN BAWAL BINTANG BAKAR KECAP (SEDANG)', 81000, 'IKAN BAWAL BINTANG BAKAR KECAP (SEDANG).jpg', 'Ikan bawal bintang memiliki daging yang empuk dan gurih. Disertai dengan kecap manis pedas, rasanya gurih dan pas untuk lauk makan. 1 ekor ikan bawal bintang bakar ukuran sedang kecap siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK133', 'IKAN BAWAL BINTANG BAKAR PEDAS (SEDANG)', 81000, 'IKAN BAWAL BINTANG BAKAR PEDAS (SEDANG).jpg', 'Ikan bawal bintang memiliki daging yang empuk dan gurih. Disertai dengan sambal pedas, rasanya pedas dan manis, pas untuk lauk makan. 1 ekor ikan bawal bintang bakar ukuran sedang pedas siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK134', 'IKAN BAWAL BINTANG BAKAR RICA (SEDANG)', 81000, 'IKAN BAWAL BINTANG BAKAR RICA (SEDANG).jpg', 'Ikan bawal bintang memiliki daging yang empuk dan gurih. Disertai dengan bumbu rica yang berwarna oranye kemerahan dengan cabe rawit yang pedas serta aroma kunyit dan potongan tomat merah, irisan bawang merah. 1 ekor ikan bawal bintang bakar ukuran sedang rica siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK135', 'IKAN BAWAL BINTANG BAKAR KECAP (BESAR)', 91000, 'IKAN BAWAL BINTANG BAKAR KECAP (BESAR).jpg', 'Ikan bawal bintang memiliki daging yang empuk dan gurih. Disertai dengan kecap manis pedas, rasanya gurih dan pas untuk lauk makan. 1 ekor ikan bawal bintang bakar ukuran besar kecap siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK136', 'IKAN BAWAL BINTANG BAKAR PEDAS (BESAR)', 91000, 'IKAN BAWAL BINTANG BAKAR PEDAS (BESAR).jpg', 'Ikan bawal bintang memiliki daging yang empuk dan gurih. Disertai dengan sambal pedas, rasanya pedas dan manis, pas untuk lauk makan. 1 ekor ikan bawal bintang bakar ukuran besar pedas siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK137', 'IKAN BAWAL BINTANG BAKAR RICA (BESAR)', 91000, 'IKAN BAWAL BINTANG BAKAR RICA (BESAR).jpg', 'Ikan bawal bintang memiliki daging yang empuk dan gurih. Disertai dengan bumbu rica yang berwarna oranye kemerahan dengan cabe rawit yang pedas serta aroma kunyit dan potongan tomat merah, irisan bawang merah. 1 ekor ikan bawal bintang bakar ukuran besar rica siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK138', 'IKAN KERAPU BAKAR PEDAS (NORMAL)', 71000, 'IKAN KERAPU BAKAR PEDAS (NORMAL).jpg', 'Ikan kerapu memiliki daging yang empuk dan gurih. Disertai dengan sambal pedas, rasanya pedas dan manis, pas untuk lauk makan. 1 ekor ikan kerapu bakar ukuran normal pedas siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK139', 'IKAN KERAPU BAKAR PEDAS (SEDANG)', 91000, 'IKAN KERAPU BAKAR PEDAS (SEDANG).jpg', 'Ikan kerapu memiliki daging yang empuk dan gurih. Disertai dengan sambal pedas, rasanya pedas dan manis, pas untuk lauk makan. 1 ekor ikan kerapu bakar ukuran sedang pedas siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK140', 'IKAN KERAPU BAKAR PEDAS (BESAR)', 91000, 'IKAN KERAPU BAKAR PEDAS (BESAR).jpg', 'Ikan kerapu memiliki daging yang empuk dan gurih. Disertai dengan sambal pedas, rasanya pedas dan manis, pas untuk lauk makan. 1 ekor ikan kerapu bakar ukuran besar pedas siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK141', 'IKAN GORENG KRISPI', 40000, 'IKAN GORENG KRISPI.jpg', 'Rasa gurih dari daging ikan yang lembut dan berpadu dengan tepung bumbu yang renyah akan membuat rasanya semakin istimewa dan krispi di mulut. 1 ekor ikan goreng krispi siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK142', 'IKAN BAKAR KECAP', 40000, 'IKAN BAKAR KECAP.jpg', 'Ikan dengan tingkat kematangan pembakaran yang pas disertai dengan kecap manis pedas, rasanya gurih dan pas untuk lauk makan. 1 ekor ikan dengan bumbu kecap siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK143', 'IKAN AYAM-AYAM SAUS MONGOLIAN', 54000, 'IKAN AYAM-AYAM SAUS MONGOLIAN.jpg', 'Saus ini terbuat dari campuran saus sambal, saus tomat dan rempah-rempah. Dengan rasa asam, pedas dan manis yang dicampur dengan irisan daging ayam dan ikan membuat kombinas pas yang siap memanjakan selera makan.'),
('MK144', 'IKAN NILA BAKAR KECAP (SEDANG)', 70000, 'IKAN NILA BAKAR KECAP (SEDANG).jpg', 'Ikan nila memiliki daging yang empuk dan gurih. Disertai dengan kecap manis pedas, rasanya gurih dan pas untuk lauk makan. 1 ekor ikan nila bakar ukuran sedang kecap siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK145', 'IKAN NILA BAKAR PEDAS (SEDANG)', 70000, 'IKAN NILA BAKAR PEDAS (SEDANG).jpg', 'Ikan nila bintang memiliki daging yang empuk dan gurih. Disertai dengan sambal pedas, rasanya pedas dan manis, pas untuk lauk makan. 1 ekor ikan nila bakar ukuran sedang pedas siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK146', 'IKAN NILA BAKAR RICA (SEDANG)', 70000, 'IKAN NILA BAKAR RICA (SEDANG).jpg', 'Ikan nila memiliki daging yang empuk dan gurih. Disertai dengan bumbu rica yang berwarna oranye kemerahan dengan cabe rawit yang pedas serta aroma kunyit dan potongan tomat merah, irisan bawang merah. 1 ekor ikan nila bakar ukuran besar rica siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK147', 'IKAN NILA BAKAR KECAP (BESAR)', 80000, 'IKAN NILA BAKAR KECAP (BESAR).jpg', 'Ikan nila memiliki daging yang empuk dan gurih. Disertai dengan kecap manis pedas, rasanya gurih dan pas untuk lauk makan. 1 ekor ikan nila bakar ukuran besar kecap siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK148', 'IKAN NILA BAKAR PEDAS (BESAR)', 80000, 'IKAN NILA BAKAR PEDAS (BESAR).jpg', 'Ikan nila bintang memiliki daging yang empuk dan gurih. Disertai dengan sambal pedas, rasanya pedas dan manis, pas untuk lauk makan. 1 ekor ikan nila bakar ukuran besar pedas siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK149', 'IKAN NILA BAKAR RICA (BESAR)', 80000, 'IKAN NILA BAKAR RICA (BESAR).jpg', 'Ikan nila memiliki daging yang empuk dan gurih. Disertai dengan bumbu rica yang berwarna oranye kemerahan dengan cabe rawit yang pedas serta aroma kunyit dan potongan tomat merah, irisan bawang merah. 1 ekor ikan nila bakar ukuran besar rica siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK150', 'IKAN GURAME BAKAR SAMBAL MATAH (SEDANG)', 80000, 'IKAN GURAME BAKAR SAMBAL MATAH (SEDANG).jpg', 'Ikan gurame bakar ini rasanya khas. Karena bumbunya adalah khas bali dengan sambal matah bali. Kelezatannya memberikan sensasi berbeda membawa kita ke pulau Dewata. Bumbu bali ini merupakan bumbu dari khas bali, dapat menghilangkan bau amis pada ikan dan tentunya rasanya menjadikan pengalaman baru saat memakan. 1 ekor ikan gurame bakar ukuran sedang sambal matah siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK151', 'IKAN GURAME BAKAR SAMBAL MATAH (BESAR)', 90000, 'IKAN GURAME BAKAR SAMBAL MATAH (BESAR).jpg', 'Ikan gurame bakar ini rasanya khas. Karena bumbunya adalah khas bali dengan sambal matah bali. Kelezatannya memberikan sensasi berbeda membawa kita ke pulau Dewata. Bumbu bali ini merupakan bumbu dari khas bali, dapat menghilangkan bau amis pada ikan dan tentunya rasanya menjadikan pengalaman baru saat memakan. 1 ekor ikan gurame bakar ukuran besar sambal matah siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK152', 'IKAN BAWAL BAKAR KECAP (NORMAL)', 71000, 'IKAN BAWAL BAKAR KECAP (NORMAL).jpg', 'Ikan bawal memiliki daging yang empuk dan gurih. Disertai dengan kecap manis pedas, rasanya gurih dan pas untuk lauk makan. 1 ekor ikan bawal bakar ukuran normal kecap siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK153', 'IKAN BAWAL BAKAR PEDAS (NORMAL)', 71000, 'IKAN BAWAL BAKAR PEDAS (NORMAL).jpg', 'Ikan bawal memiliki daging yang empuk dan gurih. Disertai dengan sambal pedas, rasanya pedas dan manis, pas untuk lauk makan. 1 ekor ikan bawal bakar ukuran normal pedas siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK154', 'IKAN BAWAL BAKAR RICA (NORMAL)', 71000, 'IKAN BAWAL BAKAR RICA (NORMAL).jpg', 'Ikan bawal memiliki daging yang empuk dan gurih. Disertai dengan bumbu rica yang berwarna oranye kemerahan dengan cabe rawit yang pedas serta aroma kunyit dan potongan tomat merah, irisan bawang merah. 1 ekor ikan bawal bakar ukuran normal rica siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK155', 'IKAN BAWAL BAKAR KECAP (SEDANG)', 81000, 'IKAN BAWAL BAKAR KECAP (SEDANG).jpg', 'Ikan bawal memiliki daging yang empuk dan gurih. Disertai dengan kecap manis pedas, rasanya gurih dan pas untuk lauk makan. 1 ekor ikan bawal bakar ukuran sedang kecap siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK156', 'IKAN BAWAL BAKAR PEDAS (SEDANG)', 81000, 'IKAN BAWAL BAKAR PEDAS (SEDANG).jpg', 'Ikan bawal memiliki daging yang empuk dan gurih. Disertai dengan sambal pedas, rasanya pedas dan manis, pas untuk lauk makan. 1 ekor ikan bawal bakar ukuran sedang pedas siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK157', 'IKAN BAWAL BAKAR RICA (SEDANG)', 81000, 'IKAN BAWAL BAKAR RICA (SEDANG).jpg', 'Ikan bawal memiliki daging yang empuk dan gurih. Disertai dengan bumbu rica yang berwarna oranye kemerahan dengan cabe rawit yang pedas serta aroma kunyit dan potongan tomat merah, irisan bawang merah. 1 ekor ikan bawal bakar ukuran sedang rica siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK158', 'IKAN BAWAL BAKAR KECAP (BESAR)', 91000, 'IKAN BAWAL BAKAR KECAP (BESAR).jpg', 'Ikan bawal memiliki daging yang empuk dan gurih. Disertai dengan kecap manis pedas, rasanya gurih dan pas untuk lauk makan. 1 ekor ikan bawal bakar ukuran besar kecap siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK159', 'IKAN BAWAL BAKAR PEDAS (BESAR)', 91000, 'IKAN BAWAL BAKAR PEDAS (BESAR).jpg', 'Ikan bawal memiliki daging yang empuk dan gurih. Disertai dengan sambal pedas, rasanya pedas dan manis, pas untuk lauk makan. 1 ekor ikan bawal bakar ukuran besar pedas siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK160', 'IKAN BAWAL BAKAR RICA (BESAR)', 91000, 'IKAN BAWAL BAKAR RICA (BESAR).jpg', 'Ikan bawal memiliki daging yang empuk dan gurih. Disertai dengan bumbu rica yang berwarna oranye kemerahan dengan cabe rawit yang pedas serta aroma kunyit dan potongan tomat merah, irisan bawang merah. 1 ekor ikan bawal bakar ukuran besar rica siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK161', 'IKAN BANDENG GORENG TEPUNG', 54000, 'IKAN BANDENG GORENG TEPUNG.jpg', 'Rasa gurih dari daging ikan bandeng yang lembut dan berpadu dengan tepung bumbu yang renyah akan membuat rasanya semakin istimewa. 1 ekor ikan bandeng goreng tepung siap memanjakan selera makan kamu dalam 1 porsi.'),
('MK162', 'KEPITING JANTAN SAUS PADANG (NORMAL)', 68000, 'KEPITING JANTAN SAUS PADANG (NORMAL).jpg', 'Pilihan lain untuk para pecinta kuliner makanan pedas. Rasa pedas yang ada di masakan saus padang berasal dari cabe matang pohon yang masih segar. Dibumbui dengan garam, bawang putih, bawang merah, pala, dan cabe merah yang dihaluskan serta bawang bombai, dan sedikit jahe. Dikombinasikan dengan saus tomat dan saus sambal. 1 Ekor Kepiting Jantan ukuran normal Saus Padang siap memanjakan selera makan kamu dengan merasakan sensasi pedasnya dalam 1 porsi.'),
('MK163', 'KEPITING JANTAN SAUS LADA HITAM (NORMAL)', 68000, 'KEPITING JANTAN SAUS LADA HITAM (NORMAL).jpg', 'Pilihan lain untuk para pecinta kuliner makanan pedas. Kepiting yang merah dibalut dengan bumbu lada hitam yang hitam berkilau dan bergenang minyak. Aroma lada hitam jelas menyengat, berpadu dengan aroma sereh dan jahe yang kuat. 1 Ekor Kepiting Jantan ukuran normal Saus Lada Hitam siap memanjakan selera makan kamu dengan rasa asin dan gurihnya yang pas dan nikmat dalam 1 porsi.'),
('MK164', 'KEPITING JANTAN SAUS PADANG (SEDANG)', 81000, 'KEPITING JANTAN SAUS PADANG (SEDANG).jpg', 'Pilihan lain untuk para pecinta kuliner makanan pedas. Rasa pedas yang ada di masakan saus padang berasal dari cabe matang pohon yang masih segar. Dibumbui dengan garam, bawang putih, bawang merah, pala, dan cabe merah yang dihaluskan serta bawang bombai, dan sedikit jahe. Dikombinasikan dengan saus tomat dan saus sambal. 1 Ekor Kepiting Jantan ukuran sedang Saus Padang siap memanjakan selera makan kamu dengan merasakan sensasi pedasnya dalam 1 porsi.'),
('MK165', 'KEPITING JANTAN SAUS LADA HITAM (SEDANG)', 81000, 'KEPITING JANTAN SAUS LADA HITAM (SEDANG).jpg', 'Pilihan lain untuk para pecinta kuliner makanan pedas. Kepiting yang merah dibalut dengan bumbu lada hitam yang hitam berkilau dan bergenang minyak. Aroma lada hitam jelas menyengat, berpadu dengan aroma sereh dan jahe yang kuat. 1 Ekor Kepiting Jantan ukuran sedang Saus Lada Hitam siap memanjakan selera makan kamu dengan rasa asin dan gurihnya yang pas dan nikmat dalam 1 porsi.'),
('MK166', 'KEPITING JANTAN SAUS PADANG (BESAR)', 98000, 'KEPITING JANTAN SAUS PADANG (BESAR).jpg', 'Pilihan lain untuk para pecinta kuliner makanan pedas. Rasa pedas yang ada di masakan saus padang berasal dari cabe matang pohon yang masih segar. Dibumbui dengan garam, bawang putih, bawang merah, pala, dan cabe merah yang dihaluskan serta bawang bombai, dan sedikit jahe. Dikombinasikan dengan saus tomat dan saus sambal. 1 Ekor Kepiting Jantan ukuran besar Saus Padang siap memanjakan selera makan kamu dengan merasakan sensasi pedasnya dalam 1 porsi.'),
('MK167', 'KEPITING JANTAN SAUS LADA HITAM (BESAR)', 98000, 'KEPITING JANTAN SAUS LADA HITAM (BESAR).jpg', 'Pilihan lain untuk para pecinta kuliner makanan pedas. Kepiting yang merah dibalut dengan bumbu lada hitam yang hitam berkilau dan bergenang minyak. Aroma lada hitam jelas menyengat, berpadu dengan aroma sereh dan jahe yang kuat. 1 Ekor Kepiting Jantan ukuran besar Saus Lada Hitam siap memanjakan selera makan kamu dengan rasa asin dan gurihnya yang pas dan nikmat dalam 1 porsi.'),
('MK168', 'KEPITING JANTAN SAUS PADANG (DUO)', 98000, 'KEPITING JANTAN SAUS PADANG (DUO).jpg', 'Pilihan lain untuk para pecinta kuliner makanan pedas. Rasa pedas yang ada di masakan saus padang berasal dari cabe matang pohon yang masih segar. Dibumbui dengan garam, bawang putih, bawang merah, pala, dan cabe merah yang dihaluskan serta bawang bombai, dan sedikit jahe. Dikombinasikan dengan saus tomat dan saus sambal. 2 Ekor Kepiting Jantan ukuran normal Saus Padang siap memanjakan selera makan kamu dengan merasakan sensasi pedasnya dalam 1 porsi.'),
('MK169', 'KEPITING JANTAN SAUS LADA HITAM (DUO)', 98000, 'KEPITING JANTAN SAUS LADA HITAM (DUO).jpg', 'Pilihan lain untuk para pecinta kuliner makanan pedas. Kepiting yang merah dibalut dengan bumbu lada hitam yang hitam berkilau dan bergenang minyak. Aroma lada hitam jelas menyengat, berpadu dengan aroma sereh dan jahe yang kuat. 2 Ekor Kepiting Jantan ukuran normal Saus Lada Hitam siap memanjakan selera makan kamu dengan rasa asin dan gurihnya yang pas dan nikmat dalam 1 porsi.'),
('MK170', 'KEPITING JANTAN SAUS ASAM MANIS (NORMAL)', 68000, 'KEPITING JANTAN SAUS ASAM MANIS (NORMAL).jpg', 'Pilihan lain untuk para pecinta kuliner makanan pedas. Jahe Merah Kalimantan menjadi ciri khas dari saos ini adalah dari salah satu bahannya, Selain untuk penetralisir kolesterol yang dikonsumsi, juga membuat rasa nya lebih khas dan sulit untuk dilupakan. Dipadukan dengan rasa asam dari rempah-rempah yang biasa dibuat untuk saus asam manis, membuat rasa pedas yang unik. 1 Ekor Kepiting Jantan ukuran normal Saos Asam Manis siap memanjakan selera makan kamu dengan rasa pedas manis yang segar dalam 1 porsi.'),
('MK171', 'KEPITING JANTAN SAUS TELUR ASIN (NORMAL)', 68000, 'KEPITING JANTAN SAUS TELUR ASIN (NORMAL).jpg', 'Rasa telur asinnya berasal dari telur asin terbaik dan berkualitas dengan warna kuning telur yang terang. Ditumis dengan margarin atau mentega yang juga punya cita rasa yang sedikit asin. Guyuran saus telur asinnya membuat rasa khas terhadap daging kepiting yang lembut. 1 Ekor Kepiting Jantan ukuran normal Saus Telur Asin siap memanjakan selera makan kamu dengan merasakan rasa telur asin yang khas dalam 1 porsi.'),
('MK172', 'KEPITING JANTAN SAUS ASAM MANIS (SEDANG)', 81000, 'KEPITING JANTAN SAUS ASAM MANIS (SEDANG).jpg', 'Pilihan lain untuk para pecinta kuliner makanan pedas. Jahe Merah Kalimantan menjadi ciri khas dari saos ini adalah dari salah satu bahannya, Selain untuk penetralisir kolesterol yang dikonsumsi, juga membuat rasa nya lebih khas dan sulit untuk dilupakan. Dipadukan dengan rasa asam dari rempah-rempah yang biasa dibuat untuk saus asam manis, membuat rasa pedas yang unik. 1 Ekor Kepiting Jantan ukuran sedang Saos Asam Manis siap memanjakan selera makan kamu dengan rasa pedas manis yang segar dalam 1 porsi.'),
('MK173', 'KEPITING JANTAN SAUS TELUR ASIN (SEDANG)', 81000, 'KEPITING JANTAN SAUS TELUR ASIN (SEDANG).jpg', 'Rasa telur asinnya berasal dari telur asin terbaik dan berkualitas dengan warna kuning telur yang terang. Ditumis dengan margarin atau mentega yang juga punya cita rasa yang sedikit asin. Guyuran saus telur asinnya membuat rasa khas terhadap daging kepiting yang lembut. 1 Ekor Kepiting Jantan ukuran sedang Saus Telur Asin siap memanjakan selera makan kamu dengan merasakan rasa telur asin yang khas dalam 1 porsi.'),
('MK174', 'KEPITING JANTAN SAUS ASAM MANIS (BESAR)', 98000, 'KEPITING JANTAN SAUS ASAM MANIS (BESAR).jpg', 'Pilihan lain untuk para pecinta kuliner makanan pedas. Jahe Merah Kalimantan menjadi ciri khas dari saos ini adalah dari salah satu bahannya, Selain untuk penetralisir kolesterol yang dikonsumsi, juga membuat rasa nya lebih khas dan sulit untuk dilupakan. Dipadukan dengan rasa asam dari rempah-rempah yang biasa dibuat untuk saus asam manis, membuat rasa pedas yang unik. 1 Ekor Kepiting Jantan ukuran besar Saos Asam Manis siap memanjakan selera makan kamu dengan rasa pedas manis yang segar dalam 1 porsi.'),
('MK175', 'KEPITING JANTAN SAUS TELUR ASIN (BESAR)', 98000, 'KEPITING JANTAN SAUS TELUR ASIN (BESAR).jpg', 'Rasa telur asinnya berasal dari telur asin terbaik dan berkualitas dengan warna kuning telur yang terang. Ditumis dengan margarin atau mentega yang juga punya cita rasa yang sedikit asin. Guyuran saus telur asinnya membuat rasa khas terhadap daging kepiting yang lembut. 1 Ekor Kepiting Jantan ukuran besar Saus Telur Asin siap memanjakan selera makan kamu dengan merasakan rasa telur asin yang khas dalam 1 porsi.');
INSERT INTO `menu` (`id_menu`, `nama_menu`, `harga`, `gambar`, `deskripsi`) VALUES
('MK176', 'KEPITING JANTAN SAUS ASAM MANIS (DUO)', 98000, 'KEPITING JANTAN SAUS ASAM MANIS (DUO).jpg', 'Pilihan lain untuk para pecinta kuliner makanan pedas. Jahe Merah Kalimantan menjadi ciri khas dari saos ini adalah dari salah satu bahannya, Selain untuk penetralisir kolesterol yang dikonsumsi, juga membuat rasa nya lebih khas dan sulit untuk dilupakan. Dipadukan dengan rasa asam dari rempah-rempah yang biasa dibuat untuk saus asam manis, membuat rasa pedas yang unik. 2 Ekor Kepiting Jantan ukuran normal Saos Asam Manis siap memanjakan selera makan kamu dengan rasa pedas manis yang segar dalam 1 porsi.'),
('MK177', 'KEPITING JANTAN SAUS TELUR ASIN (DUO)', 98000, 'KEPITING JANTAN SAUS TELUR ASIN (DUO).jpg', 'Rasa telur asinnya berasal dari telur asin terbaik dan berkualitas dengan warna kuning telur yang terang. Ditumis dengan margarin atau mentega yang juga punya cita rasa yang sedikit asin. Guyuran saus telur asinnya membuat rasa khas terhadap daging kepiting yang lembut. 2 Ekor Kepiting Jantan ukuran besar Saus Telur Asin siap memanjakan selera makan kamu dengan merasakan rasa telur asin yang khas dalam 1 porsi.'),
('MK178', 'PAKET COMBO BRONZE', 21000, 'PAKET COMBO BRONZE.jpg', 'Merupakan salah satu paket D’Cost Delivery.  Combo Bronze adalah paket termurah yang cukup komplit dibandingkan dengan paket delivery lain. Terdapat banyak pilihan paket bronze dan beberapa merupakan chief recommendation.'),
('MK179', 'PAKET COMBO SILVER', 26000, 'PAKET COMBO SILVER.jpg', 'Merupakan salah satu paket D’Cost Delivery. Combo Silver adalah paket dengan isi yang paling  lengkap dibandingkan dengan paket delivery lain. Terdapat banyak pilihan paket silver dan beberapa merupakan chief recommendation.'),
('MK180', 'PAKET COMBO GOLD', 36000, 'PAKET COMBO GOLD.jpg', 'Merupakan salah satu paket D’Cost Delivery. Combo Gold adalah paket dengan harga yang cukup terjangkau dan komplit dibandingkan dengan paket delivery lain. Terdapat banyak pilihan paket gold dan beberapa merupakan chief recommendation.'),
('MK181', 'PAKET COMBO PLATINUM', 46000, 'PAKET COMBO PLATINUM.jpg', 'Merupakan salah satu paket D’Cost Delivery. Combo Platinum adalah paket dengan isi yang lengkap dibandingkan dengan paket delivery lain. Terdapat banyak pilihan paket platinum dan beberapa merupakan chief recommendation.'),
('MN001', 'TEH TAWAR', 0, 'TEH TAWAR.jpg', 'Daun teh segar diambil dari kebun teh pilihan'),
('MN002', 'ES TEH TAWAR', 0, 'ES TEH TAWAR.jpg', 'Daun teh segar diambil dari kebun teh pilihan ditambah dengan es batu'),
('MN003', 'TEH MANIS', 0, 'TEH MANIS.jpg', 'Daun teh segar diambil dari kebun teh pilihan yang diolah dengan gula pasir terbaik'),
('MN004', 'ES TEH MANIS', 0, 'ES TEH MANIS.jpg', 'Daun teh segar diambil dari kebun teh pilihan yang diolah dengan gula pasir dan es batu terbaik'),
('MN005', 'AIR MINERAL', 4000, 'AIR MINERAL.jpg', 'Air mineral yang diperoleh dari mata air terbaik dan pilihan'),
('MN006', 'ES KRIM (VANILA + CHOCOCHIP)', 18000, 'ES KRIM (VANILA + CHOCOCHIP).jpg', 'Es Krim pilihan dengan rasa vanila dan diberi taburan chocochip'),
('MN007', 'ES LEMON TEA', 14000, 'ES LEMON TEA.jpg', 'Daun teh dan Lemon segar dari pilihan terbaik dengan tambahan es batu sebagai penyegar'),
('MN008', 'ES KELAPA MUDA', 20000, 'ES KELAPA MUDA.jpg', 'Kepala Muda segar dari pilihan terbaik dengan tambahan es batu sebagai penyegar'),
('MN009', 'ES JERUK NIPIS', 18000, 'ES JERUK NIPIS.jpg', 'Jeruk Nipis segar dari pilihan terbaik dengan tambahan es batu sebagai penyegar'),
('MN010', 'ES JERUK PERAS', 18000, 'ES JERUK PERAS.jpg', 'Jeruk Peras segar dari pilihan terbaik dengan tambahan es batu sebagai penyegar'),
('MN011', 'ES MILO', 18000, 'ES MILO.jpg', 'Kesegaran minuman Milo yang diberi tambahan es batu'),
('MN012', 'ES JERUK KELAPA MUDA', 22000, 'ES JERUK KELAPA MUDA.jpg', 'Jeruk dan Kepala Muda segar dari pilihan terbaik dengan tambahan es batu sebagai penyegar'),
('MN013', 'ICED GREENTEA BODO', 22000, 'ICED GREENTEA BODO.jpg', 'Daun teh hijau segar dari pilihan terbaik dengan tambahan es batu sebagai penyegar'),
('MN014', 'ES KRIM BODO', 18000, 'ES KRIM BODO.jpg', 'Es Krim spesial dengan citarasa tinggi'),
('MN015', 'JUS ALPUKAT', 25000, 'JUS ALPUKAT.jpg', 'Alpukat segar dari pilihan terbaik yang di-blend es batu sebagai penyegar'),
('MN016', 'JUS JAMBU MERAH', 18000, 'JUS JAMBU MERAH.jpg', 'Jambu Merah segar dari pilihan terbaik yang di-blend es batu sebagai penyegar'),
('MN017', 'JUS SIRSAK', 18000, 'JUS SIRSAK.jpg', 'Sirsak segar dari pilihan terbaik yang di-blend es batu sebagai penyegar'),
('MN018', 'FANTA FLOAT', 18000, 'FANTA FLOAT.jpg', 'Minuman Fanta yang diberi tambahan Es Krim dan es batu pilihan terbaik sebagai penyegar'),
('MN019', 'COCA-COLA FLOAT', 18000, 'COCA-COLA FLOAT.jpg', 'Minuman Coca-Cola yang diberi tambahan Es Krim dan es batu pilihan terbaik sebagai penyegar'),
('MN020', 'SPRITE FLOAT', 18000, 'SPRITE FLOAT.jpg', 'Minuman Sprite yang diberi tambahan Es Krim dan es batu pilihan terbaik sebagai penyegar'),
('MN021', 'FANTA', 12000, 'FANTA.jpg', 'Minuman Fanta yang diberi tambahan es batu sebagai penyegar'),
('MN022', 'COCA-COLA', 12000, 'COCA-COLA.jpg', 'Minuman Coca-Cola yang diberi tambahan es batu sebagai penyegar'),
('MN023', 'SPRITE', 12000, 'SPRITE.jpg', 'Minuman Sprite yang diberi tambahan es batu sebagai penyegar'),
('MN024', 'JUS TERONG BELANDA', 18000, 'JUS TERONG BELANDA.jpg', 'Terong Belanda segar dari pilihan terbaik yang di-blend es batu sebagai penyegar');

-- --------------------------------------------------------

--
-- Table structure for table `pembeli`
--

CREATE TABLE IF NOT EXISTS `pembeli` (
  `no` int(11) NOT NULL AUTO_INCREMENT,
  `id_transaksi` varchar(12) NOT NULL,
  `waktu` time NOT NULL,
  `no_meja` varchar(2) NOT NULL,
  `id_menu` varchar(5) NOT NULL,
  `jumlah` int(3) NOT NULL,
  `status` int(11) NOT NULL,
  PRIMARY KEY (`no`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=277 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
